// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEmptyAPI creates a new Empty instance
func NewEmptyAPI(spec *loads.Document) *EmptyAPI {
	return &EmptyAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		GetHandler: GetHandlerFunc(func(params GetParams) middleware.Responder {
			return middleware.NotImplemented("operation Get has not yet been implemented")
		}),
		GetAccountAllHandler: GetAccountAllHandlerFunc(func(params GetAccountAllParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAccountAll has not yet been implemented")
		}),
		GetAccountMyHandler: GetAccountMyHandlerFunc(func(params GetAccountMyParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAccountMy has not yet been implemented")
		}),
		GetAccountNumHandler: GetAccountNumHandlerFunc(func(params GetAccountNumParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAccountNum has not yet been implemented")
		}),
		GetAccountNumBalanceHandler: GetAccountNumBalanceHandlerFunc(func(params GetAccountNumBalanceParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAccountNumBalance has not yet been implemented")
		}),
		GetBalanceMyHandler: GetBalanceMyHandlerFunc(func(params GetBalanceMyParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBalanceMy has not yet been implemented")
		}),
		GetBlockHashOrHeightHandler: GetBlockHashOrHeightHandlerFunc(func(params GetBlockHashOrHeightParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBlockHashOrHeight has not yet been implemented")
		}),
		GetTxHashHandler: GetTxHashHandlerFunc(func(params GetTxHashParams) middleware.Responder {
			return middleware.NotImplemented("operation GetTxHash has not yet been implemented")
		}),
		GetTxpoolCheckHashHandler: GetTxpoolCheckHashHandlerFunc(func(params GetTxpoolCheckHashParams) middleware.Responder {
			return middleware.NotImplemented("operation GetTxpoolCheckHash has not yet been implemented")
		}),
		PostNodeAddrHandler: PostNodeAddrHandlerFunc(func(params PostNodeAddrParams) middleware.Responder {
			return middleware.NotImplemented("operation PostNodeAddr has not yet been implemented")
		}),
		PostTxpoolSendHandler: PostTxpoolSendHandlerFunc(func(params PostTxpoolSendParams) middleware.Responder {
			return middleware.NotImplemented("operation PostTxpoolSend has not yet been implemented")
		}),
	}
}

/*EmptyAPI the  API */
type EmptyAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// GetHandler sets the operation handler for the get operation
	GetHandler GetHandler
	// GetAccountAllHandler sets the operation handler for the get account all operation
	GetAccountAllHandler GetAccountAllHandler
	// GetAccountMyHandler sets the operation handler for the get account my operation
	GetAccountMyHandler GetAccountMyHandler
	// GetAccountNumHandler sets the operation handler for the get account num operation
	GetAccountNumHandler GetAccountNumHandler
	// GetAccountNumBalanceHandler sets the operation handler for the get account num balance operation
	GetAccountNumBalanceHandler GetAccountNumBalanceHandler
	// GetBalanceMyHandler sets the operation handler for the get balance my operation
	GetBalanceMyHandler GetBalanceMyHandler
	// GetBlockHashOrHeightHandler sets the operation handler for the get block hash or height operation
	GetBlockHashOrHeightHandler GetBlockHashOrHeightHandler
	// GetTxHashHandler sets the operation handler for the get tx hash operation
	GetTxHashHandler GetTxHashHandler
	// GetTxpoolCheckHashHandler sets the operation handler for the get txpool check hash operation
	GetTxpoolCheckHashHandler GetTxpoolCheckHashHandler
	// PostNodeAddrHandler sets the operation handler for the post node addr operation
	PostNodeAddrHandler PostNodeAddrHandler
	// PostTxpoolSendHandler sets the operation handler for the post txpool send operation
	PostTxpoolSendHandler PostTxpoolSendHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *EmptyAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *EmptyAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *EmptyAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *EmptyAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *EmptyAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *EmptyAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *EmptyAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the EmptyAPI
func (o *EmptyAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetHandler == nil {
		unregistered = append(unregistered, "GetHandler")
	}
	if o.GetAccountAllHandler == nil {
		unregistered = append(unregistered, "GetAccountAllHandler")
	}
	if o.GetAccountMyHandler == nil {
		unregistered = append(unregistered, "GetAccountMyHandler")
	}
	if o.GetAccountNumHandler == nil {
		unregistered = append(unregistered, "GetAccountNumHandler")
	}
	if o.GetAccountNumBalanceHandler == nil {
		unregistered = append(unregistered, "GetAccountNumBalanceHandler")
	}
	if o.GetBalanceMyHandler == nil {
		unregistered = append(unregistered, "GetBalanceMyHandler")
	}
	if o.GetBlockHashOrHeightHandler == nil {
		unregistered = append(unregistered, "GetBlockHashOrHeightHandler")
	}
	if o.GetTxHashHandler == nil {
		unregistered = append(unregistered, "GetTxHashHandler")
	}
	if o.GetTxpoolCheckHashHandler == nil {
		unregistered = append(unregistered, "GetTxpoolCheckHashHandler")
	}
	if o.PostNodeAddrHandler == nil {
		unregistered = append(unregistered, "PostNodeAddrHandler")
	}
	if o.PostTxpoolSendHandler == nil {
		unregistered = append(unregistered, "PostTxpoolSendHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *EmptyAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *EmptyAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *EmptyAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *EmptyAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *EmptyAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *EmptyAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the  API
func (o *EmptyAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *EmptyAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = NewGet(o.context, o.GetHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/all"] = NewGetAccountAll(o.context, o.GetAccountAllHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/my"] = NewGetAccountMy(o.context, o.GetAccountMyHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/{num}"] = NewGetAccountNum(o.context, o.GetAccountNumHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/account/{num}/balance"] = NewGetAccountNumBalance(o.context, o.GetAccountNumBalanceHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/balance/my"] = NewGetBalanceMy(o.context, o.GetBalanceMyHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/block/{hash_or_height}"] = NewGetBlockHashOrHeight(o.context, o.GetBlockHashOrHeightHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tx/{hash}"] = NewGetTxHash(o.context, o.GetTxHashHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/txpool/check/{hash}"] = NewGetTxpoolCheckHash(o.context, o.GetTxpoolCheckHashHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/node/{addr}"] = NewPostNodeAddr(o.context, o.PostNodeAddrHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/txpool/send"] = NewPostTxpoolSend(o.context, o.PostTxpoolSendHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *EmptyAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *EmptyAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *EmptyAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *EmptyAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *EmptyAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
