// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAccountNumOKCode is the HTTP code returned for type GetAccountNumOK
const GetAccountNumOKCode int = 200

/*GetAccountNumOK OK

swagger:response getAccountNumOK
*/
type GetAccountNumOK struct {
}

// NewGetAccountNumOK creates GetAccountNumOK with default headers values
func NewGetAccountNumOK() *GetAccountNumOK {

	return &GetAccountNumOK{}
}

// WriteResponse to the client
func (o *GetAccountNumOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetAccountNumBadRequestCode is the HTTP code returned for type GetAccountNumBadRequest
const GetAccountNumBadRequestCode int = 400

/*GetAccountNumBadRequest Error

swagger:response getAccountNumBadRequest
*/
type GetAccountNumBadRequest struct {

	/*error text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetAccountNumBadRequest creates GetAccountNumBadRequest with default headers values
func NewGetAccountNumBadRequest() *GetAccountNumBadRequest {

	return &GetAccountNumBadRequest{}
}

// WithPayload adds the payload to the get account num bad request response
func (o *GetAccountNumBadRequest) WithPayload(payload string) *GetAccountNumBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account num bad request response
func (o *GetAccountNumBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountNumBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
