// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTxHashHandlerFunc turns a function with the right signature into a get tx hash handler
type GetTxHashHandlerFunc func(GetTxHashParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTxHashHandlerFunc) Handle(params GetTxHashParams) middleware.Responder {
	return fn(params)
}

// GetTxHashHandler interface for that can handle valid get tx hash params
type GetTxHashHandler interface {
	Handle(GetTxHashParams) middleware.Responder
}

// NewGetTxHash creates a new http.Handler for the get tx hash operation
func NewGetTxHash(ctx *middleware.Context, handler GetTxHashHandler) *GetTxHash {
	return &GetTxHash{Context: ctx, Handler: handler}
}

/*GetTxHash swagger:route GET /tx/{hash} getTxHash

get the tx by hash

*/
type GetTxHash struct {
	Context *middleware.Context
	Handler GetTxHashHandler
}

func (o *GetTxHash) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTxHashParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
