// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTxHashOKCode is the HTTP code returned for type GetTxHashOK
const GetTxHashOKCode int = 200

/*GetTxHashOK OK

swagger:response getTxHashOK
*/
type GetTxHashOK struct {
}

// NewGetTxHashOK creates GetTxHashOK with default headers values
func NewGetTxHashOK() *GetTxHashOK {

	return &GetTxHashOK{}
}

// WriteResponse to the client
func (o *GetTxHashOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetTxHashBadRequestCode is the HTTP code returned for type GetTxHashBadRequest
const GetTxHashBadRequestCode int = 400

/*GetTxHashBadRequest Error

swagger:response getTxHashBadRequest
*/
type GetTxHashBadRequest struct {
}

// NewGetTxHashBadRequest creates GetTxHashBadRequest with default headers values
func NewGetTxHashBadRequest() *GetTxHashBadRequest {

	return &GetTxHashBadRequest{}
}

// WriteResponse to the client
func (o *GetTxHashBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
