// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAccountAllOKCode is the HTTP code returned for type GetAccountAllOK
const GetAccountAllOKCode int = 200

/*GetAccountAllOK OK

swagger:response getAccountAllOK
*/
type GetAccountAllOK struct {
}

// NewGetAccountAllOK creates GetAccountAllOK with default headers values
func NewGetAccountAllOK() *GetAccountAllOK {

	return &GetAccountAllOK{}
}

// WriteResponse to the client
func (o *GetAccountAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetAccountAllBadRequestCode is the HTTP code returned for type GetAccountAllBadRequest
const GetAccountAllBadRequestCode int = 400

/*GetAccountAllBadRequest Error

swagger:response getAccountAllBadRequest
*/
type GetAccountAllBadRequest struct {
}

// NewGetAccountAllBadRequest creates GetAccountAllBadRequest with default headers values
func NewGetAccountAllBadRequest() *GetAccountAllBadRequest {

	return &GetAccountAllBadRequest{}
}

// WriteResponse to the client
func (o *GetAccountAllBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
