// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBlockAtHeightParams creates a new GetBlockAtHeightParams object
// no default values defined in spec.
func NewGetBlockAtHeightParams() GetBlockAtHeightParams {

	return GetBlockAtHeightParams{}
}

// GetBlockAtHeightParams contains all the bound params for the get block at height operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetBlockAtHeight
type GetBlockAtHeightParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*height of the block
	  Required: true
	  In: path
	*/
	Height int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBlockAtHeightParams() beforehand.
func (o *GetBlockAtHeightParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHeight, rhkHeight, _ := route.Params.GetOK("height")
	if err := o.bindHeight(rHeight, rhkHeight, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHeight binds and validates parameter Height from path.
func (o *GetBlockAtHeightParams) bindHeight(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("height", "path", "int64", raw)
	}
	o.Height = value

	return nil
}
