// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostNodeAddrOKCode is the HTTP code returned for type PostNodeAddrOK
const PostNodeAddrOKCode int = 200

/*PostNodeAddrOK OK

swagger:response postNodeAddrOK
*/
type PostNodeAddrOK struct {
}

// NewPostNodeAddrOK creates PostNodeAddrOK with default headers values
func NewPostNodeAddrOK() *PostNodeAddrOK {

	return &PostNodeAddrOK{}
}

// WriteResponse to the client
func (o *PostNodeAddrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostNodeAddrBadRequestCode is the HTTP code returned for type PostNodeAddrBadRequest
const PostNodeAddrBadRequestCode int = 400

/*PostNodeAddrBadRequest Error

swagger:response postNodeAddrBadRequest
*/
type PostNodeAddrBadRequest struct {

	/*error text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostNodeAddrBadRequest creates PostNodeAddrBadRequest with default headers values
func NewPostNodeAddrBadRequest() *PostNodeAddrBadRequest {

	return &PostNodeAddrBadRequest{}
}

// WithPayload adds the payload to the post node addr bad request response
func (o *PostNodeAddrBadRequest) WithPayload(payload string) *PostNodeAddrBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post node addr bad request response
func (o *PostNodeAddrBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNodeAddrBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
