// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostTxpoolSendParams creates a new PostTxpoolSendParams object
// no default values defined in spec.
func NewPostTxpoolSendParams() PostTxpoolSendParams {

	return PostTxpoolSendParams{}
}

// PostTxpoolSendParams contains all the bound params for the post txpool send operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostTxpoolSend
type PostTxpoolSendParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*send the tx
	  Required: true
	  In: body
	*/
	Tx interface{}
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTxpoolSendParams() beforehand.
func (o *PostTxpoolSendParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body interface{}
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("tx", "body"))
			} else {
				res = append(res, errors.NewParseError("tx", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.Tx = body
		}
	} else {
		res = append(res, errors.Required("tx", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
