// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTxpoolSendOKCode is the HTTP code returned for type PostTxpoolSendOK
const PostTxpoolSendOKCode int = 200

/*PostTxpoolSendOK OK

swagger:response postTxpoolSendOK
*/
type PostTxpoolSendOK struct {
}

// NewPostTxpoolSendOK creates PostTxpoolSendOK with default headers values
func NewPostTxpoolSendOK() *PostTxpoolSendOK {

	return &PostTxpoolSendOK{}
}

// WriteResponse to the client
func (o *PostTxpoolSendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostTxpoolSendBadRequestCode is the HTTP code returned for type PostTxpoolSendBadRequest
const PostTxpoolSendBadRequestCode int = 400

/*PostTxpoolSendBadRequest Error

swagger:response postTxpoolSendBadRequest
*/
type PostTxpoolSendBadRequest struct {

	/*error text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostTxpoolSendBadRequest creates PostTxpoolSendBadRequest with default headers values
func NewPostTxpoolSendBadRequest() *PostTxpoolSendBadRequest {

	return &PostTxpoolSendBadRequest{}
}

// WithPayload adds the payload to the post txpool send bad request response
func (o *PostTxpoolSendBadRequest) WithPayload(payload string) *PostTxpoolSendBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post txpool send bad request response
func (o *PostTxpoolSendBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTxpoolSendBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
