// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPostTxpoolSendRawTxParams creates a new PostTxpoolSendRawTxParams object
// no default values defined in spec.
func NewPostTxpoolSendRawTxParams() PostTxpoolSendRawTxParams {

	return PostTxpoolSendRawTxParams{}
}

// PostTxpoolSendRawTxParams contains all the bound params for the post txpool send raw tx operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostTxpoolSendRawTx
type PostTxpoolSendRawTxParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*raw of the tx
	  Required: true
	  In: path
	*/
	RawTx string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTxpoolSendRawTxParams() beforehand.
func (o *PostTxpoolSendRawTxParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRawTx, rhkRawTx, _ := route.Params.GetOK("rawTx")
	if err := o.bindRawTx(rRawTx, rhkRawTx, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRawTx binds and validates parameter RawTx from path.
func (o *PostTxpoolSendRawTxParams) bindRawTx(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RawTx = raw

	return nil
}
