// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p.proto

package ngtypes

import (
	bytes "bytes"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type P2PHeader struct {
	NetworkId int32  `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Uuid      string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Broadcast bool   `protobuf:"varint,4,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	PeerKey   []byte `protobuf:"bytes,5,opt,name=peer_key,json=peerKey,proto3" json:"peer_key,omitempty"`
	Sign      []byte `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *P2PHeader) Reset()      { *m = P2PHeader{} }
func (*P2PHeader) ProtoMessage() {}
func (*P2PHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}
func (m *P2PHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *P2PHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PHeader.Merge(m, src)
}
func (m *P2PHeader) XXX_Size() int {
	return m.Size()
}
func (m *P2PHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PHeader.DiscardUnknown(m)
}

var xxx_messageInfo_P2PHeader proto.InternalMessageInfo

func (m *P2PHeader) GetNetworkId() int32 {
	if m != nil {
		return m.NetworkId
	}
	return 0
}

func (m *P2PHeader) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *P2PHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *P2PHeader) GetBroadcast() bool {
	if m != nil {
		return m.Broadcast
	}
	return false
}

func (m *P2PHeader) GetPeerKey() []byte {
	if m != nil {
		return m.PeerKey
	}
	return nil
}

func (m *P2PHeader) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// a protocol define a set of requests and responses
type P2PMessage struct {
	Header  *P2PHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nonce   uint64     `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Payload []byte     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *P2PMessage) Reset()      { *m = P2PMessage{} }
func (*P2PMessage) ProtoMessage() {}
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}
func (m *P2PMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *P2PMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_P2PMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *P2PMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMessage.Merge(m, src)
}
func (m *P2PMessage) XXX_Size() int {
	return m.Size()
}
func (m *P2PMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMessage.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMessage proto.InternalMessageInfo

func (m *P2PMessage) GetHeader() *P2PHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *P2PMessage) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *P2PMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PingPongPayload struct {
	BlockHeight     uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	VaultHeight     uint64 `protobuf:"varint,2,opt,name=vault_height,json=vaultHeight,proto3" json:"vault_height,omitempty"`
	LatestBlockHash []byte `protobuf:"bytes,3,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	LatestVaultHash []byte `protobuf:"bytes,4,opt,name=latest_vault_hash,json=latestVaultHash,proto3" json:"latest_vault_hash,omitempty"`
}

func (m *PingPongPayload) Reset()      { *m = PingPongPayload{} }
func (*PingPongPayload) ProtoMessage() {}
func (*PingPongPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}
func (m *PingPongPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingPongPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingPongPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingPongPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongPayload.Merge(m, src)
}
func (m *PingPongPayload) XXX_Size() int {
	return m.Size()
}
func (m *PingPongPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongPayload proto.InternalMessageInfo

func (m *PingPongPayload) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PingPongPayload) GetVaultHeight() uint64 {
	if m != nil {
		return m.VaultHeight
	}
	return 0
}

func (m *PingPongPayload) GetLatestBlockHash() []byte {
	if m != nil {
		return m.LatestBlockHash
	}
	return nil
}

func (m *PingPongPayload) GetLatestVaultHash() []byte {
	if m != nil {
		return m.LatestVaultHash
	}
	return nil
}

type GetChainPayload struct {
	VaultHeight uint64 `protobuf:"varint,1,opt,name=vault_height,json=vaultHeight,proto3" json:"vault_height,omitempty"`
}

func (m *GetChainPayload) Reset()      { *m = GetChainPayload{} }
func (*GetChainPayload) ProtoMessage() {}
func (*GetChainPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}
func (m *GetChainPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetChainPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetChainPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetChainPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainPayload.Merge(m, src)
}
func (m *GetChainPayload) XXX_Size() int {
	return m.Size()
}
func (m *GetChainPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainPayload proto.InternalMessageInfo

func (m *GetChainPayload) GetVaultHeight() uint64 {
	if m != nil {
		return m.VaultHeight
	}
	return 0
}

type ChainPayload struct {
	Vault        *Vault   `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Blocks       []*Block `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	LatestHeight uint64   `protobuf:"varint,3,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
}

func (m *ChainPayload) Reset()      { *m = ChainPayload{} }
func (*ChainPayload) ProtoMessage() {}
func (*ChainPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{4}
}
func (m *ChainPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainPayload.Merge(m, src)
}
func (m *ChainPayload) XXX_Size() int {
	return m.Size()
}
func (m *ChainPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ChainPayload proto.InternalMessageInfo

func (m *ChainPayload) GetVault() *Vault {
	if m != nil {
		return m.Vault
	}
	return nil
}

func (m *ChainPayload) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ChainPayload) GetLatestHeight() uint64 {
	if m != nil {
		return m.LatestHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*P2PHeader)(nil), "ngtypes.P2PHeader")
	proto.RegisterType((*P2PMessage)(nil), "ngtypes.P2PMessage")
	proto.RegisterType((*PingPongPayload)(nil), "ngtypes.PingPongPayload")
	proto.RegisterType((*GetChainPayload)(nil), "ngtypes.GetChainPayload")
	proto.RegisterType((*ChainPayload)(nil), "ngtypes.ChainPayload")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0x86, 0xbd, 0x17, 0x27, 0x39, 0x4f, 0x02, 0x11, 0x2b, 0x0a, 0x73, 0x82, 0x95, 0x31, 0x08,
	0x59, 0x57, 0xa4, 0x08, 0xf7, 0x04, 0x47, 0xc1, 0x21, 0x84, 0x64, 0x6d, 0x41, 0x1b, 0x6d, 0xe2,
	0x95, 0x6d, 0x25, 0x67, 0x5b, 0xde, 0x0d, 0xc8, 0x1d, 0xbc, 0x01, 0x8f, 0x01, 0x15, 0xaf, 0x41,
	0x99, 0xf2, 0x4a, 0xe2, 0x34, 0x94, 0xf7, 0x08, 0xc8, 0xb3, 0xcb, 0x5d, 0x22, 0xba, 0x9d, 0x7f,
	0x7e, 0xcf, 0x7c, 0xf3, 0xcb, 0xe0, 0x55, 0xb3, 0x6a, 0x5a, 0xd5, 0xa5, 0x2e, 0xe9, 0xb0, 0x48,
	0x75, 0x53, 0x49, 0x75, 0x36, 0x5a, 0xac, 0xcb, 0xe5, 0xca, 0xa8, 0x67, 0xa3, 0x4f, 0x62, 0xb3,
	0xd6, 0xa6, 0x08, 0x7f, 0x10, 0xf0, 0xe2, 0x59, 0x7c, 0x25, 0x45, 0x22, 0x6b, 0xfa, 0x0c, 0xa0,
	0x90, 0xfa, 0x73, 0x59, 0xaf, 0xe6, 0x79, 0xe2, 0x93, 0x80, 0x44, 0x7d, 0xee, 0x59, 0xe5, 0x5d,
	0x42, 0x29, 0xb8, 0x9b, 0x4d, 0x9e, 0xf8, 0x27, 0x01, 0x89, 0x3c, 0x8e, 0x6f, 0xfa, 0x14, 0x3c,
	0x9d, 0x5f, 0x4b, 0xa5, 0xc5, 0x75, 0xe5, 0xf7, 0x02, 0x12, 0xf5, 0xf8, 0xbd, 0xd0, 0x75, 0x17,
	0x75, 0x29, 0x92, 0xa5, 0x50, 0xda, 0x77, 0x03, 0x12, 0x9d, 0xf2, 0x7b, 0x81, 0x3e, 0x81, 0xd3,
	0x4a, 0xca, 0x7a, 0xbe, 0x92, 0x8d, 0xdf, 0x0f, 0x48, 0x34, 0xe6, 0xc3, 0xae, 0x7e, 0x2f, 0x9b,
	0x6e, 0x95, 0xca, 0xd3, 0xc2, 0x1f, 0xa0, 0x8c, 0xef, 0x30, 0x03, 0x88, 0x67, 0xf1, 0x07, 0xa9,
	0x94, 0x48, 0x25, 0x3d, 0x87, 0x41, 0x86, 0xd4, 0xc8, 0x39, 0x9a, 0xd1, 0xa9, 0xbd, 0x76, 0x7a,
	0x77, 0x0f, 0xb7, 0x0e, 0xfa, 0x18, 0xfa, 0x45, 0x59, 0x2c, 0x25, 0x92, 0xbb, 0xdc, 0x14, 0xd4,
	0x87, 0x61, 0x25, 0x9a, 0x75, 0x29, 0x12, 0x04, 0xef, 0xb6, 0x9b, 0x32, 0xfc, 0x49, 0x60, 0x12,
	0xe7, 0x45, 0x1a, 0x97, 0x45, 0x1a, 0x1b, 0x8d, 0x3e, 0x87, 0x31, 0xa6, 0x38, 0xcf, 0x64, 0x9e,
	0x66, 0x1a, 0xb7, 0xba, 0xdc, 0x24, 0x7b, 0x85, 0x52, 0x67, 0xc1, 0x6c, 0xff, 0x59, 0xcc, 0x36,
	0x93, 0xb7, 0xb5, 0x9c, 0xc3, 0xa3, 0xb5, 0xd0, 0x52, 0xe9, 0xb9, 0x1d, 0x26, 0x54, 0x66, 0xb7,
	0x4f, 0x4c, 0xe3, 0x12, 0x07, 0x0a, 0x95, 0x1d, 0x78, 0xed, 0xd4, 0xce, 0xeb, 0x1e, 0x7a, 0x3f,
	0xe2, 0x64, 0xa1, 0xb2, 0xf0, 0x02, 0x26, 0x6f, 0xa5, 0x7e, 0x93, 0x89, 0xbc, 0x38, 0x00, 0x3e,
	0xa2, 0x21, 0xff, 0xd1, 0x84, 0x5f, 0x09, 0x8c, 0x8f, 0xbe, 0x79, 0x09, 0x7d, 0xec, 0xdb, 0x4c,
	0x1f, 0xde, 0x65, 0x8a, 0x9b, 0xb8, 0x69, 0xd2, 0x57, 0x30, 0x40, 0x7a, 0xe5, 0x9f, 0x04, 0xbd,
	0x23, 0x1b, 0xc2, 0x73, 0xdb, 0xa5, 0x2f, 0xe0, 0x81, 0x3d, 0xc0, 0x22, 0xf4, 0x10, 0x61, 0x6c,
	0x44, 0xc3, 0x70, 0x79, 0xb1, 0xdd, 0x31, 0xe7, 0x66, 0xc7, 0x9c, 0xdb, 0x1d, 0x23, 0x5f, 0x5a,
	0x46, 0xbe, 0xb7, 0x8c, 0xfc, 0x6a, 0x19, 0xd9, 0xb6, 0x8c, 0xfc, 0x6e, 0x19, 0xf9, 0xd3, 0x32,
	0xe7, 0xb6, 0x65, 0xe4, 0xdb, 0x9e, 0x39, 0xdb, 0x3d, 0x73, 0x6e, 0xf6, 0xcc, 0x59, 0x0c, 0xf0,
	0xf7, 0x7d, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x9d, 0x36, 0x66, 0xee, 0x02, 0x00, 0x00,
}

func (this *P2PHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*P2PHeader)
	if !ok {
		that2, ok := that.(P2PHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NetworkId != that1.NetworkId {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.Broadcast != that1.Broadcast {
		return false
	}
	if !bytes.Equal(this.PeerKey, that1.PeerKey) {
		return false
	}
	if !bytes.Equal(this.Sign, that1.Sign) {
		return false
	}
	return true
}
func (this *P2PMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*P2PMessage)
	if !ok {
		that2, ok := that.(P2PMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Header.Equal(that1.Header) {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.Payload, that1.Payload) {
		return false
	}
	return true
}
func (this *PingPongPayload) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PingPongPayload)
	if !ok {
		that2, ok := that.(PingPongPayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BlockHeight != that1.BlockHeight {
		return false
	}
	if this.VaultHeight != that1.VaultHeight {
		return false
	}
	if !bytes.Equal(this.LatestBlockHash, that1.LatestBlockHash) {
		return false
	}
	if !bytes.Equal(this.LatestVaultHash, that1.LatestVaultHash) {
		return false
	}
	return true
}
func (this *GetChainPayload) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetChainPayload)
	if !ok {
		that2, ok := that.(GetChainPayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VaultHeight != that1.VaultHeight {
		return false
	}
	return true
}
func (this *ChainPayload) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChainPayload)
	if !ok {
		that2, ok := that.(ChainPayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Vault.Equal(that1.Vault) {
		return false
	}
	if len(this.Blocks) != len(that1.Blocks) {
		return false
	}
	for i := range this.Blocks {
		if !this.Blocks[i].Equal(that1.Blocks[i]) {
			return false
		}
	}
	if this.LatestHeight != that1.LatestHeight {
		return false
	}
	return true
}
func (this *P2PHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&ngtypes.P2PHeader{")
	s = append(s, "NetworkId: "+fmt.Sprintf("%#v", this.NetworkId)+",\n")
	s = append(s, "Uuid: "+fmt.Sprintf("%#v", this.Uuid)+",\n")
	s = append(s, "Timestamp: "+fmt.Sprintf("%#v", this.Timestamp)+",\n")
	s = append(s, "Broadcast: "+fmt.Sprintf("%#v", this.Broadcast)+",\n")
	s = append(s, "PeerKey: "+fmt.Sprintf("%#v", this.PeerKey)+",\n")
	s = append(s, "Sign: "+fmt.Sprintf("%#v", this.Sign)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *P2PMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&ngtypes.P2PMessage{")
	if this.Header != nil {
		s = append(s, "Header: "+fmt.Sprintf("%#v", this.Header)+",\n")
	}
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "Payload: "+fmt.Sprintf("%#v", this.Payload)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PingPongPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&ngtypes.PingPongPayload{")
	s = append(s, "BlockHeight: "+fmt.Sprintf("%#v", this.BlockHeight)+",\n")
	s = append(s, "VaultHeight: "+fmt.Sprintf("%#v", this.VaultHeight)+",\n")
	s = append(s, "LatestBlockHash: "+fmt.Sprintf("%#v", this.LatestBlockHash)+",\n")
	s = append(s, "LatestVaultHash: "+fmt.Sprintf("%#v", this.LatestVaultHash)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetChainPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&ngtypes.GetChainPayload{")
	s = append(s, "VaultHeight: "+fmt.Sprintf("%#v", this.VaultHeight)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ChainPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&ngtypes.ChainPayload{")
	if this.Vault != nil {
		s = append(s, "Vault: "+fmt.Sprintf("%#v", this.Vault)+",\n")
	}
	if this.Blocks != nil {
		s = append(s, "Blocks: "+fmt.Sprintf("%#v", this.Blocks)+",\n")
	}
	s = append(s, "LatestHeight: "+fmt.Sprintf("%#v", this.LatestHeight)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringP2P(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *P2PHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *P2PHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sign) > 0 {
		i -= len(m.Sign)
		copy(dAtA[i:], m.Sign)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Sign)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PeerKey) > 0 {
		i -= len(m.PeerKey)
		copy(dAtA[i:], m.PeerKey)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.PeerKey)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Broadcast {
		i--
		if m.Broadcast {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.NetworkId != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.NetworkId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *P2PMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *P2PMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *P2PMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Nonce != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintP2P(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PingPongPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingPongPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingPongPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LatestVaultHash) > 0 {
		i -= len(m.LatestVaultHash)
		copy(dAtA[i:], m.LatestVaultHash)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.LatestVaultHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LatestBlockHash) > 0 {
		i -= len(m.LatestBlockHash)
		copy(dAtA[i:], m.LatestBlockHash)
		i = encodeVarintP2P(dAtA, i, uint64(len(m.LatestBlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.VaultHeight != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.VaultHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.BlockHeight != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetChainPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetChainPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetChainPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VaultHeight != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.VaultHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ChainPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestHeight != 0 {
		i = encodeVarintP2P(dAtA, i, uint64(m.LatestHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Blocks) > 0 {
		for iNdEx := len(m.Blocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Blocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintP2P(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Vault != nil {
		{
			size, err := m.Vault.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintP2P(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintP2P(dAtA []byte, offset int, v uint64) int {
	offset -= sovP2P(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *P2PHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NetworkId != 0 {
		n += 1 + sovP2P(uint64(m.NetworkId))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovP2P(uint64(m.Timestamp))
	}
	if m.Broadcast {
		n += 2
	}
	l = len(m.PeerKey)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.Sign)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	return n
}

func (m *P2PMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovP2P(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovP2P(uint64(m.Nonce))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	return n
}

func (m *PingPongPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovP2P(uint64(m.BlockHeight))
	}
	if m.VaultHeight != 0 {
		n += 1 + sovP2P(uint64(m.VaultHeight))
	}
	l = len(m.LatestBlockHash)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	l = len(m.LatestVaultHash)
	if l > 0 {
		n += 1 + l + sovP2P(uint64(l))
	}
	return n
}

func (m *GetChainPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VaultHeight != 0 {
		n += 1 + sovP2P(uint64(m.VaultHeight))
	}
	return n
}

func (m *ChainPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vault != nil {
		l = m.Vault.Size()
		n += 1 + l + sovP2P(uint64(l))
	}
	if len(m.Blocks) > 0 {
		for _, e := range m.Blocks {
			l = e.Size()
			n += 1 + l + sovP2P(uint64(l))
		}
	}
	if m.LatestHeight != 0 {
		n += 1 + sovP2P(uint64(m.LatestHeight))
	}
	return n
}

func sovP2P(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozP2P(x uint64) (n int) {
	return sovP2P(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *P2PHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&P2PHeader{`,
		`NetworkId:` + fmt.Sprintf("%v", this.NetworkId) + `,`,
		`Uuid:` + fmt.Sprintf("%v", this.Uuid) + `,`,
		`Timestamp:` + fmt.Sprintf("%v", this.Timestamp) + `,`,
		`Broadcast:` + fmt.Sprintf("%v", this.Broadcast) + `,`,
		`PeerKey:` + fmt.Sprintf("%v", this.PeerKey) + `,`,
		`Sign:` + fmt.Sprintf("%v", this.Sign) + `,`,
		`}`,
	}, "")
	return s
}
func (this *P2PMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&P2PMessage{`,
		`Header:` + strings.Replace(this.Header.String(), "P2PHeader", "P2PHeader", 1) + `,`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`Payload:` + fmt.Sprintf("%v", this.Payload) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingPongPayload) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingPongPayload{`,
		`BlockHeight:` + fmt.Sprintf("%v", this.BlockHeight) + `,`,
		`VaultHeight:` + fmt.Sprintf("%v", this.VaultHeight) + `,`,
		`LatestBlockHash:` + fmt.Sprintf("%v", this.LatestBlockHash) + `,`,
		`LatestVaultHash:` + fmt.Sprintf("%v", this.LatestVaultHash) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetChainPayload) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetChainPayload{`,
		`VaultHeight:` + fmt.Sprintf("%v", this.VaultHeight) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ChainPayload) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForBlocks := "[]*Block{"
	for _, f := range this.Blocks {
		repeatedStringForBlocks += strings.Replace(fmt.Sprintf("%v", f), "Block", "Block", 1) + ","
	}
	repeatedStringForBlocks += "}"
	s := strings.Join([]string{`&ChainPayload{`,
		`Vault:` + strings.Replace(fmt.Sprintf("%v", this.Vault), "Vault", "Vault", 1) + `,`,
		`Blocks:` + repeatedStringForBlocks + `,`,
		`LatestHeight:` + fmt.Sprintf("%v", this.LatestHeight) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringP2P(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *P2PHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: P2PHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: P2PHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			m.NetworkId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NetworkId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Broadcast", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Broadcast = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerKey = append(m.PeerKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PeerKey == nil {
				m.PeerKey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sign", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sign = append(m.Sign[:0], dAtA[iNdEx:postIndex]...)
			if m.Sign == nil {
				m.Sign = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *P2PMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: P2PMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: P2PMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &P2PHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingPongPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingPongPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingPongPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultHeight", wireType)
			}
			m.VaultHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VaultHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestBlockHash = append(m.LatestBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LatestBlockHash == nil {
				m.LatestBlockHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVaultHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestVaultHash = append(m.LatestVaultHash[:0], dAtA[iNdEx:postIndex]...)
			if m.LatestVaultHash == nil {
				m.LatestVaultHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetChainPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetChainPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetChainPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultHeight", wireType)
			}
			m.VaultHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VaultHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vault", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vault == nil {
				m.Vault = &Vault{}
			}
			if err := m.Vault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthP2P
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthP2P
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blocks = append(m.Blocks, &Block{})
			if err := m.Blocks[len(m.Blocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			m.LatestHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipP2P(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthP2P
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipP2P(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowP2P
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowP2P
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthP2P
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupP2P
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthP2P
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthP2P        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowP2P          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupP2P = fmt.Errorf("proto: unexpected end of group")
)
