// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TxHeader tx header
//
// swagger:model txHeader
type TxHeader struct {

	// convener
	Convener int64 `json:"convener,omitempty"`

	// extra
	Extra string `json:"extra,omitempty"`

	// fee
	Fee float64 `json:"fee,omitempty"`

	// nonce
	Nonce int64 `json:"nonce,omitempty"`

	// participants
	Participants []string `json:"participants"`

	// type
	Type int64 `json:"type,omitempty"`

	// values
	Values []float64 `json:"values"`
}

// Validate validates this tx header
func (m *TxHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TxHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TxHeader) UnmarshalBinary(b []byte) error {
	var res TxHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
